---
- name: Playbook to create user, group and assigning user into a group
  hosts: web
  tasks: 
    - name: Create a group called dba
      group: 
        name: dba
        state: present

    - name: Create an user & assigning user into dba group    
      user:
        name: john
        state: present
        groups: dba  
